### ISSUE TITLE
Le garde fou ne parvient pas à restaurer les onglets perdus

### ISSUE THREAD

**Issue by MjstcQueentin** [RNbowKing/SmartNetBrowser#4]
listOfTabs devient NULL à la ligne 1005 de BrowserForm.vb ce qui empêche le programme de poursuivre.

```
Case "RestorePreviousSession"
  Dim listOfTabs As New Specialized.StringCollection
  listOfTabs = My.Settings.LastSessionListOfTabs
  For index = 0 To listOfTabs.Count - 1
    AddTab(listOfTabs.Item(index), BrowserTabs)
  Next
  My.Settings.CorrectlyClosed = False
```

**Comment by MjstcQueentin** [comment]
Après modifications (voir commit https://github.com/SmartNetApps/SmartNetBrowser/commit/e6aefb20af5ccb9972955a5f25c0a1511fcf3d36), l'erreur NullException ne survient plus.
En revanche, la restauration n'est faite que pour la première page de la liste. Les suivantes ne sont pas restaurées.

```
Case "RestorePreviousSession"
  For Each page As String In My.Settings.LastSessionListOfTabs
    AddTab(page, BrowserTabs)
  Next
  My.Settings.CorrectlyClosed = False
```
```
Public Sub RefreshListOfTabs()
  Dim WB As CustomBrowser
  Dim newList As New Specialized.StringCollection
  For Each onglet As TabPage In BrowserTabs.TabPages
    WB = CType(onglet.Tag, CustomBrowser)
    newList.Add(WB.Url.ToString())
  Next
  My.Settings.LastSessionListOfTabs = newList
  My.Settings.Save()
End Sub
```

**Comment by RNbowKing** [comment]
Partiellement corrigé suite aux commits https://github.com/RNbowKing/SmartNetBrowser/commit/9c8221f4bac6ee249ac2a086cd59ee5c7c2a0dc5 https://github.com/RNbowKing/SmartNetBrowser/commit/4ae2427fba6cd9ca124dfbe0138f51f345faa2bd et https://github.com/RNbowKing/SmartNetBrowser/commit/665c954c9e0395c56ae76961167c178583ec9a25
